// <auto-generated />
using System;
using CarRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220055307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("color");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<int>("ModelGenerationId")
                        .HasColumnType("int")
                        .HasColumnName("model_generation_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelGenerationId");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            LicensePlate = "A001AA163",
                            ModelGenerationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            LicensePlate = "B777BC163",
                            ModelGenerationId = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            LicensePlate = "C123ET163",
                            ModelGenerationId = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "Green",
                            LicensePlate = "E555KH163",
                            ModelGenerationId = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "Silver",
                            LicensePlate = "K234MR163",
                            ModelGenerationId = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "Gray",
                            LicensePlate = "M888OA163",
                            ModelGenerationId = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = "Blue",
                            LicensePlate = "N456RS163",
                            ModelGenerationId = 7
                        },
                        new
                        {
                            Id = 8,
                            Color = "Brown",
                            LicensePlate = "O789TU163",
                            ModelGenerationId = 8
                        },
                        new
                        {
                            Id = 9,
                            Color = "White",
                            LicensePlate = "P321XO163",
                            ModelGenerationId = 9
                        },
                        new
                        {
                            Id = 10,
                            Color = "Black",
                            LicensePlate = "S654AM163",
                            ModelGenerationId = 10
                        },
                        new
                        {
                            Id = 11,
                            Color = "Orange",
                            LicensePlate = "T987RE163",
                            ModelGenerationId = 11
                        },
                        new
                        {
                            Id = 12,
                            Color = "White",
                            LicensePlate = "U246KN163",
                            ModelGenerationId = 12
                        },
                        new
                        {
                            Id = 13,
                            Color = "Black",
                            LicensePlate = "H135VT163",
                            ModelGenerationId = 13
                        },
                        new
                        {
                            Id = 14,
                            Color = "Gray",
                            LicensePlate = "SH579SA163",
                            ModelGenerationId = 14
                        },
                        new
                        {
                            Id = 15,
                            Color = "Blue",
                            LicensePlate = "SCH864RO163",
                            ModelGenerationId = 15
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("body_type");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("class");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("drive_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SeatsCount")
                        .HasColumnType("int")
                        .HasColumnName("seats_count");

                    b.HasKey("Id");

                    b.ToTable("car_models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Sedan",
                            Class = "Premium",
                            DriveType = "RWD",
                            Name = "BMW 3 Series",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Coupe",
                            Class = "Sports",
                            DriveType = "RWD",
                            Name = "Ford Mustang",
                            SeatsCount = 4
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Sedan",
                            Class = "Compact",
                            DriveType = "FWD",
                            Name = "Honda Civic",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "SUV",
                            Class = "Off-road",
                            DriveType = "4WD",
                            Name = "Jeep Wrangler",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 5,
                            BodyType = "Coupe",
                            Class = "Luxury",
                            DriveType = "RWD",
                            Name = "Porsche 911",
                            SeatsCount = 4
                        },
                        new
                        {
                            Id = 6,
                            BodyType = "SUV",
                            Class = "Full-size",
                            DriveType = "AWD",
                            Name = "Chevrolet Tahoe",
                            SeatsCount = 8
                        },
                        new
                        {
                            Id = 7,
                            BodyType = "Sedan",
                            Class = "Economy",
                            DriveType = "FWD",
                            Name = "Lada Vesta",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 8,
                            BodyType = "SUV",
                            Class = "Mid-size",
                            DriveType = "AWD",
                            Name = "Subaru Outback",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 9,
                            BodyType = "Van",
                            Class = "Commercial",
                            DriveType = "RWD",
                            Name = "GAZ Gazelle Next",
                            SeatsCount = 3
                        },
                        new
                        {
                            Id = 10,
                            BodyType = "Hatchback",
                            Class = "Hybrid",
                            DriveType = "FWD",
                            Name = "Toyota Prius",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 11,
                            BodyType = "SUV",
                            Class = "Off-road",
                            DriveType = "4WD",
                            Name = "UAZ Patriot",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 12,
                            BodyType = "SUV",
                            Class = "Premium",
                            DriveType = "AWD",
                            Name = "Lexus RX",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 13,
                            BodyType = "SUV",
                            Class = "Luxury",
                            DriveType = "AWD",
                            Name = "Range Rover Sport",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 14,
                            BodyType = "Sedan",
                            Class = "Premium",
                            DriveType = "AWD",
                            Name = "Audi A4",
                            SeatsCount = 5
                        },
                        new
                        {
                            Id = 15,
                            BodyType = "SUV",
                            Class = "Off-road",
                            DriveType = "4WD",
                            Name = "Lada Niva Travel",
                            SeatsCount = 5
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("license_number");

                    b.HasKey("Id");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1988, 3, 15),
                            FullName = "Alexander Smirnov",
                            LicenseNumber = "2023-001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1992, 7, 22),
                            FullName = "Marina Kovalenko",
                            LicenseNumber = "2022-045"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1995, 11, 10),
                            FullName = "Denis Popov",
                            LicenseNumber = "2024-012"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1985, 5, 3),
                            FullName = "Elena Vasnetsova",
                            LicenseNumber = "2021-078"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1990, 9, 30),
                            FullName = "Igor Kozlovsky",
                            LicenseNumber = "2023-056"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1993, 2, 14),
                            FullName = "Anna Orlova",
                            LicenseNumber = "2022-123"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1987, 8, 18),
                            FullName = "Artem Belov",
                            LicenseNumber = "2024-034"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1994, 12, 25),
                            FullName = "Sofia Grigorieva",
                            LicenseNumber = "2021-099"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1991, 6, 7),
                            FullName = "Pavel Melnikov",
                            LicenseNumber = "2023-087"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1989, 4, 12),
                            FullName = "Olga Zakharova",
                            LicenseNumber = "2022-067"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1996, 10, 28),
                            FullName = "Mikhail Tikhonov",
                            LicenseNumber = "2024-005"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1986, 1, 19),
                            FullName = "Ksenia Fedorova",
                            LicenseNumber = "2021-112"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1997, 7, 3),
                            FullName = "Roman Sokolov",
                            LicenseNumber = "2023-092"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1984, 3, 22),
                            FullName = "Tatiana Krylova",
                            LicenseNumber = "2022-031"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1998, 11, 15),
                            FullName = "Andrey Davydov",
                            LicenseNumber = "2024-021"
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EngineVolume")
                        .HasColumnType("float")
                        .HasColumnName("engine_volume");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<decimal>("RentalPricePerHour")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rental_price_per_hour");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("transmission");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("model_generations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineVolume = 2.0,
                            ModelId = 1,
                            RentalPricePerHour = 2200m,
                            Transmission = "AT",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            EngineVolume = 5.0,
                            ModelId = 2,
                            RentalPricePerHour = 5000m,
                            Transmission = "AT",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            EngineVolume = 1.5,
                            ModelId = 3,
                            RentalPricePerHour = 1200m,
                            Transmission = "CVT",
                            Year = 2024
                        },
                        new
                        {
                            Id = 4,
                            EngineVolume = 3.6000000000000001,
                            ModelId = 4,
                            RentalPricePerHour = 2800m,
                            Transmission = "AT",
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            EngineVolume = 3.0,
                            ModelId = 5,
                            RentalPricePerHour = 8000m,
                            Transmission = "AT",
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            EngineVolume = 5.2999999999999998,
                            ModelId = 6,
                            RentalPricePerHour = 3500m,
                            Transmission = "AT",
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            EngineVolume = 1.6000000000000001,
                            ModelId = 7,
                            RentalPricePerHour = 700m,
                            Transmission = "MT",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            EngineVolume = 2.5,
                            ModelId = 8,
                            RentalPricePerHour = 1800m,
                            Transmission = "AT",
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            EngineVolume = 2.7000000000000002,
                            ModelId = 9,
                            RentalPricePerHour = 1500m,
                            Transmission = "MT",
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            EngineVolume = 1.8,
                            ModelId = 10,
                            RentalPricePerHour = 1600m,
                            Transmission = "CVT",
                            Year = 2023
                        },
                        new
                        {
                            Id = 11,
                            EngineVolume = 2.7000000000000002,
                            ModelId = 11,
                            RentalPricePerHour = 1400m,
                            Transmission = "MT",
                            Year = 2022
                        },
                        new
                        {
                            Id = 12,
                            EngineVolume = 3.5,
                            ModelId = 12,
                            RentalPricePerHour = 3200m,
                            Transmission = "AT",
                            Year = 2024
                        },
                        new
                        {
                            Id = 13,
                            EngineVolume = 3.0,
                            ModelId = 13,
                            RentalPricePerHour = 6000m,
                            Transmission = "AT",
                            Year = 2023
                        },
                        new
                        {
                            Id = 14,
                            EngineVolume = 2.0,
                            ModelId = 14,
                            RentalPricePerHour = 2800m,
                            Transmission = "AT",
                            Year = 2024
                        },
                        new
                        {
                            Id = 15,
                            EngineVolume = 1.7,
                            ModelId = 15,
                            RentalPricePerHour = 900m,
                            Transmission = "MT",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("car_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("rental_date");

                    b.Property<int>("RentalHours")
                        .HasColumnType("int")
                        .HasColumnName("rental_hours");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 7,
                            ClientId = 1,
                            RentalDate = new DateTime(2024, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 48
                        },
                        new
                        {
                            Id = 2,
                            CarId = 7,
                            ClientId = 3,
                            RentalDate = new DateTime(2024, 2, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 72
                        },
                        new
                        {
                            Id = 3,
                            CarId = 7,
                            ClientId = 5,
                            RentalDate = new DateTime(2024, 2, 20, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 24
                        },
                        new
                        {
                            Id = 4,
                            CarId = 1,
                            ClientId = 2,
                            RentalDate = new DateTime(2024, 2, 27, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 96
                        },
                        new
                        {
                            Id = 5,
                            CarId = 1,
                            ClientId = 4,
                            RentalDate = new DateTime(2024, 2, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 120
                        },
                        new
                        {
                            Id = 6,
                            CarId = 2,
                            ClientId = 6,
                            RentalDate = new DateTime(2024, 2, 23, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 72
                        },
                        new
                        {
                            Id = 7,
                            CarId = 2,
                            ClientId = 8,
                            RentalDate = new DateTime(2024, 2, 18, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 48
                        },
                        new
                        {
                            Id = 8,
                            CarId = 3,
                            ClientId = 7,
                            RentalDate = new DateTime(2024, 2, 28, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 36
                        },
                        new
                        {
                            Id = 9,
                            CarId = 4,
                            ClientId = 9,
                            RentalDate = new DateTime(2024, 2, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 96
                        },
                        new
                        {
                            Id = 10,
                            CarId = 5,
                            ClientId = 10,
                            RentalDate = new DateTime(2024, 2, 28, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 168
                        },
                        new
                        {
                            Id = 11,
                            CarId = 6,
                            ClientId = 11,
                            RentalDate = new DateTime(2024, 2, 22, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 72
                        },
                        new
                        {
                            Id = 12,
                            CarId = 8,
                            ClientId = 12,
                            RentalDate = new DateTime(2024, 2, 26, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 48
                        },
                        new
                        {
                            Id = 13,
                            CarId = 9,
                            ClientId = 13,
                            RentalDate = new DateTime(2024, 2, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 60
                        },
                        new
                        {
                            Id = 14,
                            CarId = 10,
                            ClientId = 14,
                            RentalDate = new DateTime(2024, 2, 24, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 96
                        },
                        new
                        {
                            Id = 15,
                            CarId = 11,
                            ClientId = 15,
                            RentalDate = new DateTime(2024, 2, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 120
                        },
                        new
                        {
                            Id = 16,
                            CarId = 12,
                            ClientId = 1,
                            RentalDate = new DateTime(2024, 2, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 48
                        },
                        new
                        {
                            Id = 17,
                            CarId = 13,
                            ClientId = 2,
                            RentalDate = new DateTime(2024, 2, 5, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 72
                        },
                        new
                        {
                            Id = 18,
                            CarId = 14,
                            ClientId = 3,
                            RentalDate = new DateTime(2024, 2, 12, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 36
                        },
                        new
                        {
                            Id = 19,
                            CarId = 15,
                            ClientId = 4,
                            RentalDate = new DateTime(2024, 2, 16, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            RentalHours = 84
                        });
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.ModelGeneration", "ModelGeneration")
                        .WithMany()
                        .HasForeignKey("ModelGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelGeneration");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.ModelGeneration", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.CarModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRental.Domain.Entities.Rental", b =>
                {
                    b.HasOne("CarRental.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
